apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    environment: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      environment: {{ .Values.namespace }}
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        environment: {{ .Values.namespace }}
        app: {{ .Release.Name }}
    spec:
  {{- if ne .Values.namespace "local" }}
      nodeSelector:
        eks.amazonaws.com/nodegroup: {{ .Values.deployment.nodeSelector.eks.nodeGroup }}
  {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
  {{- if ne .Values.namespace "local" }}
          imagePullPolicy: Always
  {{- end }}
          ports:
            - name: "http"
              containerPort: {{ .Values.deployment.containers.default.ports.http }}
{{- if ne .Values.namespace "local" }}
          resources:
            requests:
              cpu: {{ .Values.deployment.containers.default.resources.requests.cpu }}
              memory: {{ .Values.deployment.containers.default.resources.requests.memory }}
            limits:
              cpu: {{ .Values.deployment.containers.default.resources.limits.cpu }}
              memory: {{ .Values.deployment.containers.default.resources.limits.memory }}
{{- end }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.deployment.containers.default.ports.http }}
            initialDelaySeconds: {{ .Values.deployment.containers.default.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.containers.default.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.deployment.containers.default.ports.http }}
            initialDelaySeconds: {{ .Values.deployment.containers.default.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.containers.default.livenessProbe.periodSeconds }}

