apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    environment: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port.http }}
      targetPort: http
  selector:
    environment: {{ .Values.namespace }}
    app: {{ .Release.Name }}
  type: {{ .Values.service.type }}
